term.clear()
term.setCursorPos(1,1)
term.write("OS Booting...")
term.setCursorPos(1,2)
term.write("-------------")
term.setCursorPos(1,4)
sleep(1)
textutils.slowPrint("##########")
sleep(1)
shell.run("OS/Menu")